export const GET_DATA_CHART_START = `GET_DATA_CHART_START`;
export const GET_DATA_CHART_SUCSSES = `GET_DATA_CHART_SUCSSES`;
export const GET_DATA_CHART_ERROR = `GET_DATA_CHART_ERROR`;

export const GET_DATA_RANK_NEW_START = `GET_DATA_RANK_NEW_START`;
export const GET_DATA_RANK_NEW_SUCSSES = `GET_DATA_RANK_NEW_SUCSSES`;
export const GET_DATA_RANK_NEW_ERROR = `GET_DATA_RANK_NEW_ERROR`;